name: Build Ubuntu Kernel
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set kernel version
        id: kernel_version
        run: |
          sudo apt update
          sudo apt install parallel -y
          sudo apt list '?name(linux-image-[[:digit:]]+.[[:digit:]]+.[[:digit:]]+-[[:digit:]]+-generic)' | awk -F' ' '{print $2}' | tail -n1 | parallel -j1 echo "KERNEL_VERSION={}" >> "$GITHUB_OUTPUT"
      - name: Get kernel version
        env:
          KERNEL_VERSION: ${{ steps.kernel_version.outputs.KERNEL_VERSION }}
        run: echo "Kernel version is $KERNEL_VERSION"
