name: Build Ubuntu Kernel
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set tag
        id: tag
        run: |
          sudo apt update
          UBUNTU_KERNEL_VERSION="$(sudo apt list '?name(linux-image-[[:digit:]]+.[[:digit:]]+.[[:digit:]]+-[[:digit:]]+-generic)' | awk -F' ' '{print $2}' | tail -n1)"
          UBUNTU_TAG="Ubuntu-$UBUNTU_KERNEL_VERSION"
          echo "UBUNTU_TAG=$UBUNTU_TAG" >> $GITHUB_OUTPUT
      - name: Checkout Ubuntu kernel
        env:
          UBUNTU_TAG: ${{ steps.tag.outputs.UBUNTU_TAG }}
        run: |
          git clone --depth 1 --branch $UBUNTU_TAG git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/noble
